language: objective-c

osx_image: xcode10
xcode_workspace: "Fritz!Box Kit.xcworkspace"
xcode_scheme: Example App
xcode_sdk: iphonesimulator11.0

script: xcodebuild build test -workspace "Fritz!Box Kit.xcworkspace" -scheme "Example App" -destination "platform=iOS Simulator,name=iPhone 7" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
